@Library('nodejs-app')_

pipeline {
    agent any

    tools {nodejs "node"}

    environment {
        NEXUS_IP = '104.248.243.228'
    }

    stages {
        stage("Increment version") {
            steps {
                script {
                    dir('08-jenkins/node-project/app') {
                        incrementVersion()
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('08-jenkins/node-project/app') {
                        test()
                    }
                }
            }
        }

        stage('Docker image') {
            steps {
                script {
                    dir('08-jenkins/node-project/app') {
                        dockerImage "${env.NEXUS_IP}:8888/repository/nodejs-app:${IMAGE_VERSION}" "${NEXUS_IP}:8888"
                    }
                }
            }
        }

        stage('Git push') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_PASSWORD')]) {
                        sh 'git config --global user.name "jenkins"'
                        sh 'git config --global user.email "jenkins@example.com"'
                        sh "git remote set-url origin https://${GITHUB_USER}:${GITHUB_PASSWORD}@github.com/mikhalchenko-alexander/devops-bootcamp.git"
                        sh "git add 08-jenkins/node-project/app/package.json 08-jenkins/node-project/app/package-lock.json"
                        sh 'git commit -m "ci: version bump"'
                        sh 'git push origin HEAD:main'
                    }
                }
            }    
        }
    }
}

