pipeline {
    agent any

    tools {nodejs "node"}

    stages {
        stage('Test') {
            steps {
                script {
                    dir('08-jenkins/node-project/app') {
                        sh 'npm i'
                        sh 'npm run test'
                    }
                }
            }
        }
    }
}

