@Library('java-app')_

pipeline {
    agent any

    environment {
        ECR_REGISTRY = '458405758445.dkr.ecr.eu-central-1.amazonaws.com/11-eks-java-app'
    }

    stages {
        stage("Increment version") {
            steps {
                script {
                    dir('11-eks/java-app/app') {
                        incrementVersion()
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('11-eks/java-app/app') {
                        test()
                    }
                }
            }
        }

        stage('Docker image') {
            steps {
                script {
                    dir('11-eks/java-app/app') {
                        dockerImage "${env.ECR_REGISTRY}:${IMAGE_VERSION}", "${ECR_REGISTRY}", "eu-central-1"
                    }
                }
            }
        }

        stage('Git push') {
            steps {
                script {
                    gitPush 'github.com/mikhalchenko-alexander/devops-bootcamp.git'
                }
            }
        }
    }
}

