- name: Install Tools
  hosts: _ansible_jenkins
  become: yes
  tasks:
    - name: Install Tools
      ansible.builtin.yum:
        name:
          - java-17-amazon-corretto
          - nodejs22
          - nodejs22-npm
          - docker
        update_cache: yes
        state: present

- name: Install Jenkins
  hosts: _ansible_jenkins
  become: yes
  tasks:
    - name: Download Jenkins repository file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins-CI key
      shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
