- name: Deploy all k8s manifests
  hosts: localhost
  tasks:
    - name: Create docker registry secret directly
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: regcred
            namespace: default
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: >-
              {{
                {
                  "auths": {
                    "https://index.docker.io/v1/": {
                      "auth": (docker_user + ":" + docker_password) | b64encode
                    }
                  }
                }
                | to_json
                | b64encode
              }}

    - name: Deploy nginx ingress controller
      kubernetes.core.helm:
        name: ingress-controller
        release_namespace: ingress
        create_namespace: true
        chart_ref: ingress-nginx/ingress-nginx

    - name: Deploy all k8s manifests
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '{{ item }}') }}"
        state: present
        namespace: default
      with_fileglob:
        - "manifests/*.yaml"
