apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-bootcamp
  region: eu-central-1
  version: "1.32"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    minSize: 1
    maxSize: 3

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: java-app

addons:
  - name: aws-ebs-csi-driver
    version: latest
  - name: eks-pod-identity-agent # required for Pod Identity
    version: latest

addonsConfig:
  autoApplyPodIdentityAssociations: true
