apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-bootcamp
  region: eu-central-1
  version: "1.29"

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 3

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: java-app
