pipeline {
    agent any

    environment {
        ECR_REGISTRY = '458405758445.dkr.ecr.eu-central-1.amazonaws.com'
        ECR_REPOSITORY = '14-node-js-app'
    }

    stages {
        stage('init python env') {
            steps {
                script {
                    dir('14-automation-with-python') {
                        if (!fileExists(".venv")) {
                            sh(script: 'uv venv -p 3.12')
                        }
                        sh(script: 'uv pip install -r requirements.txt')
                    }
                }
            }
        }

        stage('select image version') {
            steps {
                script {
                    dir('14-automation-with-python') {
                        withCredentials([usernamePassword(credentialsId: 'aws', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                            def tags = sh(script: 'uv run list_image_tags.py', returnStdout: true).trim
                            selectedVersion = input(message: 'Select version to deploy', ok: 'Deploy', parameters: [choise(name: 'Select version', chouses: tags)])
                            env.DOCKER_IMAGE = "${ECR_REGISTRY}/${ECR_REPOSITORY}:${selectedVersion}"
                            echo "Selected docker image ${env.DOCKER_IMAGE}"
                        }
                    }
                }
            }
        }
    }
}
