pipeline {
    agent any

    environment {
        ECR_REGISTRY = '458405758445.dkr.ecr.eu-central-1.amazonaws.com'
        ECR_REPOSITORY = '14-node-js-app'
    }

    stages {
        stage('select image version') {
            steps {
                script {
                    def tags = sh(script: 'python3 list_image_tags.py', returnStdout: true).trim
                    selectedVersion = input(message: 'Select version to deploy', ok: 'Deploy', parameters: [choise(name: 'Select version', chouses: tags)])
                    env.DOCKER_IMAGE = "${ECR_REGISTRY}/${ECR_REPOSITORY}:${selectedVersion}"
                    echo "Selected docker image ${env.DOCKER_IMAGE}"
                }
            }
        }
    }
}
