@Library('nodejs-app')_

pipeline {
    agent any

    tools {nodejs "node"}

    stages {
        stage("Increment version") {
            when {
                expression {
                    return env.GIT_BRANCH == "main"
                }
            }
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        incrementVersion()
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        test()
                    }
                }
            }
        }

        stage('Docker image') {
            when {
                expression {
                    return env.GIT_BRANCH == "main"
                }
            }
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        env.IMAGE_NAME = "aam123/nodejs-app:${IMAGE_VERSION}"
                        dockerImage IMAGE_NAME, "docker.io"
                    }
                }
            }
        }

        stage('Git push') {
            when {
                expression {
                    return env.GIT_BRANCH == "main"
                }
            }
            steps {
                script {
                    gitPush 'github.com/mikhalchenko-alexander/devops-bootcamp.git'
                }
            }
        }

        stage('Deploy') {
            when {
                expression {
                    return env.GIT_BRANCH == "main"
                }
            }
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'nexus', usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASSWORD')]) {
                        def ec2instance = 'ubuntu@52.57.155.60'
                        def shellCmd = "bash server-cmds.sh ${IMAGE_NAME} ${NEXUS_USER} ${NEXUS_PASSWORD}"
                        sshagent(credentials: ['ec2-instance']) {
                            sh "scp -o StrictHostKeyChecking=no 09-aws/server-cmds.sh ${ec2instance}:~/"
                            sh "scp -o StrictHostKeyChecking=no 09-aws/node-project/app/docker-compose.yml ${ec2instance}:~/"
                            sh "ssh -o StrictHostKeyChecking=no ${ec2instance} ${shellCmd}"
                        }
                    }
                }
            }
        }
    }
}
