@Library('nodejs-app')_

pipeline {
    agent {
        docker {
          image 'docker:latest'
        }
    }

    tools {nodejs "node"}

    stages {
        stage("Increment version") {
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        incrementVersion()
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        test()
                    }
                }
            }
        }

        stage('Docker image') {
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        dockerImage "aam123/nodejs-app:${IMAGE_VERSION}", "hub.docker.com"
                    }
                }
            }
        }

        stage('Git push') {
            steps {
                script {
                    gitPush 'github.com/mikhalchenko-alexander/devops-bootcamp.git'
                }
            }
        }
    }
}
