@Library('nodejs-app')_

pipeline {
    agent any

    tools {nodejs "node"}

    stages {
        stage("Increment version") {
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        incrementVersion()
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        test()
                    }
                }
            }
        }

        stage('Docker image') {
            steps {
                script {
                    dir('09-aws/node-project/app') {
                        dockerImage "aam123/nodejs-app:${IMAGE_VERSION}", "docker.io"
                    }
                }
            }
        }

        stage('Git push') {
            steps {
                script {
                    gitPush 'github.com/mikhalchenko-alexander/devops-bootcamp.git'
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent(credentials: ['ec2-instance']) {
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@52.57.155.60 ls'
                }
            }
        }
    }
}
