- name: Provision Ansible instance
  hosts: localhost
  tasks:
    - name: Create Ansible instance
      amazon.aws.ec2_instance:
        key_name: devops-bootcamp
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        wait: yes
        state: running
        region: "{{ region }}"
        vpc_subnet_id: "{{ ansible_vpc_subnet_id }}"
        network_interfaces:
          - assign_public_ip: true
        security_group: "{{ security_group }}"
        name: "ansible-controller"

    - pause:
        seconds: 60
